export type DocsNavItem = {
  label: string;
  to: string;
};

export type DocsNavGroup = {
  label?: string;
  items: DocsNavItem[];
};

export const DOCS_NAV: DocsNavGroup[] = [
  {
    items: [{ label: "Overview", to: "/docs" }],
  },
  {
    label: "Foundations",
    items: [
      { label: "Colors", to: "/docs/foundations/colors" },
      { label: "Typography", to: "/docs/foundations/typography" },
      { label: "Spacing", to: "/docs/foundations/spacing" },
      { label: "Shadow", to: "/docs/foundations/shadow" },
      { label: "Radius", to: "/docs/foundations/radius" },
    ],
  },
  {
    label: "Components",
    items: [
      { label: "Accordion", to: "/docs/components/accordion" },
      { label: "Alert", to: "/docs/components/alert" },
      { label: "AlertDialog", to: "/docs/components/alert-dialog" },
      { label: "AspectRatio", to: "/docs/components/aspect-ratio" },
      { label: "Avatar", to: "/docs/components/avatar" },
      { label: "Badge", to: "/docs/components/badge" },
      { label: "Breadcrumb", to: "/docs/components/breadcrumb" },
      { label: "Button", to: "/docs/components/button" },
      { label: "Card", to: "/docs/components/card" },
      { label: "Carousel", to: "/docs/components/carousel" },
      { label: "Checkbox", to: "/docs/components/checkbox" },
      { label: "Clipboard", to: "/docs/components/clipboard" },
      { label: "Collapsible", to: "/docs/components/collapsible" },
      { label: "ColorPicker", to: "/docs/components/color-picker" },
      { label: "Combobox", to: "/docs/components/combobox" },
      { label: "Command", to: "/docs/components/command" },
      { label: "DatePicker", to: "/docs/components/date-picker" },
      { label: "Dialog", to: "/docs/components/dialog" },
      { label: "Drawer", to: "/docs/components/drawer" },
      { label: "Editable", to: "/docs/components/editable" },
      { label: "Empty", to: "/docs/components/empty" },
      { label: "Field", to: "/docs/components/field" },
      { label: "FileUpload", to: "/docs/components/file-upload" },
      { label: "Heading", to: "/docs/components/heading" },
      { label: "HoverCard", to: "/docs/components/hover-card" },
      { label: "IconButton", to: "/docs/components/icon-button" },
      { label: "Input", to: "/docs/components/input" },
      { label: "Kbd", to: "/docs/components/kbd" },
      { label: "List", to: "/docs/components/list" },
      { label: "Listbox", to: "/docs/components/listbox" },
      { label: "Menu", to: "/docs/components/menu" },
      { label: "NumberInput", to: "/docs/components/number-input" },
      { label: "Pagination", to: "/docs/components/pagination" },
      { label: "PasswordInput", to: "/docs/components/password-input" },
      { label: "PinInput", to: "/docs/components/pin-input" },
      { label: "Popover", to: "/docs/components/popover" },
      { label: "Progress", to: "/docs/components/progress" },
      { label: "QR Code", to: "/docs/components/qr-code" },
      { label: "RadioGroup", to: "/docs/components/radio-group" },
      { label: "RatingGroup", to: "/docs/components/rating-group" },
      { label: "ScrollArea", to: "/docs/components/scroll-area" },
      { label: "SegmentGroup", to: "/docs/components/segment-group" },
      { label: "Select", to: "/docs/components/select" },
      { label: "Separator", to: "/docs/components/separator" },
      { label: "Sidebar", to: "/docs/components/sidebar" },
      { label: "Skeleton", to: "/docs/components/skeleton" },
      { label: "Slider", to: "/docs/components/slider" },
      { label: "Spinner", to: "/docs/components/spinner" },
      { label: "Splitter", to: "/docs/components/splitter" },
      { label: "Stack", to: "/docs/components/stack" },
      { label: "Steps", to: "/docs/components/steps" },
      { label: "Switch", to: "/docs/components/switch" },
      { label: "Table", to: "/docs/components/table" },
      { label: "Tabs", to: "/docs/components/tabs" },
      { label: "TagsInput", to: "/docs/components/tags-input" },
      { label: "Textarea", to: "/docs/components/textarea" },
      { label: "Toast", to: "/docs/components/toast" },
      { label: "Toggle", to: "/docs/components/toggle" },
      { label: "ToggleGroup", to: "/docs/components/toggle-group" },
      { label: "Toolbar", to: "/docs/components/toolbar" },
      { label: "Tooltip", to: "/docs/components/tooltip" },
      { label: "TreeView", to: "/docs/components/tree-view" },
    ],
  },
  {
    label: "Data Visualization",
    items: [{ label: "Chart", to: "/docs/data-viz/chart" }],
  },
];
